### ISSUE TITLE
Play NOMAD opening video on app launch as splash ?

### ISSUE THREAD

**Issue by cadesalaberry** [NOMAD-Live/nomad-live-android#9]
Check this answer: http://stackoverflow.com/questions/27970759/how-to-prebuffer-videoview-a-while-another-videoview-b-is-playing-android

**Comment by felxb** [comment]
nice

*Félix Brochier*

*Nation. **Industries. **Live.*
+1 514 435 7567
http://TheNOMADS.com

**Comment by cadesalaberry** [comment]
Would take too much time to launch.
